### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by herbyisgood** [WarEmu/WarBugs#13710]
Every time i run the patcher i get the following error:
Error unpacking:
System.UnauthorizedAccessException: Access to the path 'C:\Users\Lucas\Downloads\Warhammer Online - Age of Reckoning\ICSharpCode.SharpZipLib.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at RoRLauncher.MainWindow.Unpack(String fileName)

Tried to run as administrator and redownload the client.

**Comment by sioding** [comment]
Hey - thanks for the report but this bugtracker is for ingame problems only. You can find some help using our forum: https://www.returnofreckoning.com/forum/viewforum.php?f=4
