### ISSUE TITLE
I'm new and I don't know what I am doing wrong.

### ISSUE THREAD

**Issue by xXSamyleeXx** [WarEmu/WarBugs#13854]
Every time I try to load the game, it tries to update and fails.. :(

Error Downloading updater:
System.UnauthorizedAccessException: Access to the path 'D:\games\Warhammer Online - Age of Reckoning\RoRLauncher.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at RoRUpdater.MainWindow.c7L3Zl71wSqG8TOaIO(Object , FileMode , FileAccess )
   at RoRUpdater.MainWindow.tYB114Sxk(Object  , DownloadDataCompletedEventArgs  )

**Comment by sioding** [comment]
Hey - thanks for the ticket - but this bugtracker is for ingame problems only. You can find some help here: https://www.returnofreckoning.com/forum/viewforum.php?f=4 - but tbh: my best guess is that your torrent is already running
