### ISSUE TITLE
Cant click on anything in game. Constantly have to /reload UI

### ISSUE THREAD

**Issue by Dumke** [WarEmu/WarBugs#17253]
I CAN NOT click anything. I have to constantly /reload my ui. I have removed all addons, deleted game cache, repaired game patcher and I am still having a problem.

I can click on Sc to queue but once I port in I cant click on anything. Cant grab quest, click on enemies or teammates, cant click on hotbar, cant click on scenario to see who is in it. Cant even close the scenario party window. Have to hit escape on keyboard. Keyboard functions work just no clicking. I cant even leave a scenario even after /reload. I have to let it time out. I cant click on respawn after I die. I have to /reload and hope game doesnt crash. This doesnt just happen while in a scenario happens in open rvr as well.

HELP I have tried everything I can think of.

This is the error message I am getting when I just tried to update patcher:::
Error Downloading updater:
System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Return of Reckoning\RoRLauncher.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at RoRUpdater.MainWindow.c7L3Zl71wSqG8TOaIO(Object , FileMode , FileAccess )
   at RoRUpdater.MainWindow.tYB114Sxk(Object  , DownloadDataCompletedEventArgs  )

**Comment by Kaelang** [comment]
This is one for the forums.
