### ISSUE TITLE
Try to connect, error occurs.

### ISSUE THREAD

**Issue by PraetorianOverlord** [WarEmu/WarBugs#1794]
So I'm new to this game, I installed it, followed the instructions. When I launch up the launcher and put in my info and hit connect, it gives me this message.
Error starting: System.UnauthorizedAccessException: Access to the path 'D:\Program file Data\Warhammer Online - Age of Reckoning\WAR.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at RoRLauncher.Client.patchExe()
   at RoRLauncher.Client.Handle(PacketIn packet)
After this message pops up the connect button greys out. And I've tried over and over and it still does the same thing. 
I've tried moving it to me C: drive and doing it as well but when I do it gives me the error on startup and just crashes when I hit connect. Any idea how to fix it?

**Comment by Evildoor** [comment]
Have you read 
http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2889
?

**Comment by PraetorianOverlord** [comment]
I missed that, I apologise.
