### ISSUE TITLE
What should i do with this Error

### ISSUE THREAD

**Issue by arsdvoskin** [WarEmu/WarBugs#20128]
Error: System.IO.IOException: The process cannot access the file 'D:\RoR\ReturnOfReckoning-Oct2021\Warhammer Online - Return of Reckoning\art.myp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at WarZoneLib.MYP.wdcMK4PDqje1EIyA91m(Object , FileMode , FileAccess )
   at WarZoneLib.MYP..ctor(String fileName, FileAccess access)
   at WarZoneLib.MYPManager.Get(MythicPackage archive)
   at RoRLauncher.Client.DurD3qqdCXXMhYqq6OS(MythicPackage archive)
   at RoRLauncher.Client.Handle(PacketIn packet)
   at RoRLauncher.Client.SKMvyPqOQwpkvhoJPqZ(Object )
   at RoRLauncher.Client.OnReceive(PacketIn packet)
   at RoRLauncher.Client.bEGQ8fqB16OtEsonTDI(Object )
   at RoRLauncher.Client.Nimgt80cKi(Object  )

**Comment by lilimx** [comment]
Hey,

this is no bug. This is an install issue. Restart your PC or close your Torrent correctly.

**Comment by arsdvoskin** [comment]
Thank you!!

вт, 24 мая 2022 г. в 00:19, lilimx ***@***.***>:
