### ISSUE TITLE
Game Launch: Click Connect: An Error Occured...

### ISSUE THREAD

**Issue by HunterBlackstone** [WarEmu/WarBugs#5541]
For the last couple of weeks I have had a dialog popup after clicking CONNECT with the following error:

Data.myp:
System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at MYPHandler.MYPHandler..ctor(String filename, del_FileTableEventHandler eventHandler_FileTable, del_FileEventHandler eventHandler_Extraction, HashDictionary hashDic)
   at RoRLauncher.Client.UpdateWarData()

**Comment by Evildoor** [comment]
Wrong place for such kind of problems. Read the rules of the bugtracker.
