### ISSUE TITLE
Character Select screen will not load

### ISSUE THREAD

**Issue by mlabrecque** [WarEmu/WarBugs#7586]
I got an error on login, but the launcher still launched the game. When I load in, I only get the options Cinematics, Credits, Settings and Quit. Nothing else appears on the screen, except the usual background and a black box with no content. Is there a known fix for this issue?

Data.myp:
System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Warhammer Online - Age of Reckoning\mythloginserviceconfig.xml'.
File name: 'C:\Program Files (x86)\Warhammer Online - Age of Reckoning\mythloginserviceconfig.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at RoRLauncher.Client.UpdateWarData()

**Comment by Luth-RoR** [comment]
The bugtracker is only for bugs. 
The support forum is for support. That issue is covered by by the common issues guide: https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2889
