### ISSUE TITLE
Empty Server screen

### ISSUE THREAD

**Issue by LordMalis** [WarEmu/WarBugs#7926]
Once I log into the game I have only cinematic, settings, credits, and quite buttons. No character creation, no server selection. I am also given this error text:

Data.myp:
System.IO.FileNotFoundException: Could not find file 'C:\Users\Anthony\Desktop\Warhammer Online - Age of Reckoning\mythloginserviceconfig.xml'.
File name: 'C:\Users\Anthony\Desktop\Warhammer Online - Age of Reckoning\mythloginserviceconfig.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at RoRLauncher.Client.UpdateWarData()

**Comment by milosxe** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2889
